const fs = require('fs');

const mainPath = 'src/main.jsx';
const cssPath = 'src/styles.css';

let main = fs.readFileSync(mainPath, 'utf8');
const mainStart = main.indexOf('function SurfaceGroupOverlay(');
const mainEnd = main.indexOf('function FeatureSpotlights()');
if (mainStart === -1 || mainEnd === -1 || mainEnd <= mainStart) {
  throw new Error('main.jsx anchors not found');
}

const mainReplacement = [
  'function SurfaceGroupOverlay({ group, open, slide }) {',
  '\tif (typeof document === "undefined" || !group) return null;',
  '',
  '\tconst [title, images, labels] = group;',
  '\tconst activeIndex = slide % images.length;',
  '',
  '\treturn createPortal(',
  '\t\t<div className={`surface-group-overlay${open ? " is-open" : ""}`} aria-hidden="true">',
  '\t\t\t<div className="surface-group-overlay-scrim" />',
  '\t\t\t<div className="surface-group-overlay-carousel">',
  '\t\t\t\t<figure className="surface-group-overlay-frame" key={`${title}-${activeIndex}`}>' ,
  '\t\t\t\t\t<img src={images[activeIndex]} alt="" />',
  '\t\t\t\t\t<figcaption>{labels[activeIndex]}</figcaption>',
  '\t\t\t\t</figure>',
  '\t\t\t\t<div className="surface-group-overlay-rail">',
  '\t\t\t\t\t{labels.map((label, index) => (',
  '\t\t\t\t\t\t<span key={label} className={index === activeIndex ? "is-active" : ""}>',
  '\t\t\t\t\t\t\t{label}',
  '\t\t\t\t\t\t</span>',
  '\t\t\t\t\t))}',
  '\t\t\t\t</div>',
  '\t\t\t</div>',
  '\t\t</div>,',
  '\t\tdocument.body',
  '\t);',
  '}',
  '',
  'function SurfaceGroups() {',
  '\tconst [active, setActive] = React.useState(null);',
  '\tconst [slide, setSlide] = React.useState(0);',
  '\tconst lastRef = React.useRef(0);',
  '\tconst closeTimer = React.useRef(null);',
  '\tconst canHover =',
  '\t\ttypeof window !== "undefined" && window.matchMedia("(hover: hover) and (pointer: fine)").matches;',
  '',
  '\tconst open = (index) => {',
  '\t\tif (!canHover) return;',
  '\t\tif (closeTimer.current) {',
  '\t\t\twindow.clearTimeout(closeTimer.current);',
  '\t\t\tcloseTimer.current = null;',
  '\t\t}',
  '\t\tlastRef.current = index;',
  '\t\tsetSlide(0);',
  '\t\tsetActive(index);',
  '\t};',
  '',
  '\tconst scheduleClose = (index) => {',
  '\t\tif (closeTimer.current) window.clearTimeout(closeTimer.current);',
  '\t\tcloseTimer.current = window.setTimeout(() => setActive((cur) => (cur === index ? null : cur)), 90);',
  '\t};',
  '',
  '\tReact.useEffect(() => {',
  '\t\tif (active === null) return undefined;',
  '\t\tconst timer = window.setInterval(() => setSlide((cur) => (cur + 1) % 3), 1600);',
  '\t\treturn () => window.clearInterval(timer);',
  '\t}, [active]);',
  '',
  '\tReact.useEffect(() => () => {',
  '\t\tif (closeTimer.current) window.clearTimeout(closeTimer.current);',
  '\t}, []);',
  '',
  '\treturn (',
  '\t\t<section className="section surface-groups-section reveal">',
  '\t\t\t<div className="section-heading split-heading">',
  '\t\t\t\t<div>',
  '\t\t\t\t\t<p className="eyebrow">Surface groups</p>',
  '\t\t\t\t\t<h2>Dedicated panels map to the jobs inside a run.</h2>',
  '\t\t\t\t</div>',
  '\t\t\t\t<p>',
  '\t\t\t\t\tThe screenshots are not just UI inventory. They show how Stratum separates inspection, building, review, and operations into visible surfaces. Hover a group to preview its surfaces in a focused carousel.',
  '\t\t\t\t</p>',
  '\t\t\t</div>',
  '\t\t\t<div className="surface-group-grid">',
  '\t\t\t\t{surfaceGroups.map(([title, images, labels], index) => (',
  '\t\t\t\t\t<article',
  '\t\t\t\t\t\tkey={title}',
  '\t\t\t\t\t\tclassName="surface-group-card"',
  '\t\t\t\t\t\tonPointerEnter={() => open(index)}',
  '\t\t\t\t\t\tonPointerLeave={() => scheduleClose(index)}',
  '\t\t\t\t\t>',
  '\t\t\t\t\t\t<div className="surface-group-fan">',
  '\t\t\t\t\t\t\t{images.map((src, i) => (',
  '\t\t\t\t\t\t\t\t<img key={`${title}-${src}`} src={src} alt={`${labels[i]} screenshot`} loading="lazy" />',
  '\t\t\t\t\t\t\t))}',
  '\t\t\t\t\t\t</div>',
  '\t\t\t\t\t\t<h3>{title}</h3>',
  '\t\t\t\t\t\t<div className="surface-group-labels">',
  '\t\t\t\t\t\t\t{labels.map((label) => (',
  '\t\t\t\t\t\t\t\t<span key={label}>{label}</span>',
  '\t\t\t\t\t\t\t))}',
  '\t\t\t\t\t\t</div>',
  '\t\t\t\t\t</article>',
  '\t\t\t\t))}',
  '\t\t\t</div>',
  '\t\t\t<SurfaceGroupOverlay group={surfaceGroups[lastRef.current]} open={active !== null} slide={slide} />',
  '\t\t</section>',
  '\t);',
  '}',
  '',
  ''
].join('\n');

main = main.slice(0, mainStart) + mainReplacement + main.slice(mainEnd);
fs.writeFileSync(mainPath, main);

let css = fs.readFileSync(cssPath, 'utf8');
const cssStart = css.indexOf('.surface-group-overlay-row {');
const cssEnd = css.indexOf('.surface-group-card h3 {');
if (cssStart === -1 || cssEnd === -1 || cssEnd <= cssStart) {
  throw new Error('styles.css anchors not found');
}

const cssReplacement = [
  '.surface-group-overlay-carousel {',
  '\tposition: relative;',
  '\tdisplay: grid;',
  '\tgap: 18px;',
  '\tjustify-items: center;',
  '\twidth: min(72vw, 960px);',
  '\tpadding: 0 clamp(20px, 4vw, 56px);',
  '\ttransform: translateY(22px) scale(0.96);',
  '\ttransition: transform 0.44s var(--ease-out);',
  '}',
  '',
  '.surface-group-overlay.is-open .surface-group-overlay-carousel {',
  '\ttransform: translateY(0) scale(1);',
  '}',
  '',
  '.surface-group-overlay-frame {',
  '\twidth: 100%;',
  '\tmargin: 0;',
  '\tdisplay: grid;',
  '\tgap: 14px;',
  '\tjustify-items: center;',
  '}',
  '',
  '.surface-group-overlay-frame img {',
  '\twidth: 100%;',
  '\taspect-ratio: 16 / 10;',
  '\tobject-fit: cover;',
  '\tobject-position: top left;',
  '\tborder: 1px solid rgba(255, 255, 255, 0.16);',
  '\tborder-radius: 20px;',
  '\tbackground: #fff;',
  '\tbox-shadow: 0 40px 90px -28px rgba(0, 0, 0, 0.7);',
  '}',
  '',
  '.surface-group-overlay-frame figcaption {',
  '\tfont-family: var(--font-mono);',
  '\tfont-size: clamp(12px, 1vw, 14px);',
  '\tletter-spacing: 0.04em;',
  '\tcolor: rgba(255, 255, 255, 0.94);',
  '}',
  '',
  '.surface-group-overlay-rail {',
  '\tdisplay: flex;',
  '\tflex-wrap: wrap;',
  '\tjustify-content: center;',
  '\tgap: 10px;',
  '}',
  '',
  '.surface-group-overlay-rail span {',
  '\tpadding: 7px 12px;',
  '\tborder: 1px solid rgba(255, 255, 255, 0.18);',
  '\tborder-radius: 999px;',
  '\tbackground: rgba(255, 255, 255, 0.08);',
  '\tfont-family: var(--font-mono);',
  '\tfont-size: 12px;',
  '\tletter-spacing: 0.03em;',
  '\tcolor: rgba(255, 255, 255, 0.72);',
  '\ttransition: border-color 0.25s ease, background 0.25s ease, color 0.25s ease, transform 0.25s ease;',
  '}',
  '',
  '.surface-group-overlay-rail span.is-active {',
  '\tborder-color: rgba(255, 255, 255, 0.34);',
  '\tbackground: rgba(255, 255, 255, 0.16);',
  '\tcolor: #fff;',
  '\ttransform: translateY(-1px);',
  '}',
  '',
  ''
].join('\n');

css = css.slice(0, cssStart) + cssReplacement + css.slice(cssEnd);
fs.writeFileSync(cssPath, css);

console.log('patched surface groups');
